apiVersion: v1
kind: Service
metadata:
  name: taskpulse-service
  namespace: cicd-demo
  labels:
    app: taskpulse-api
    managed-by: github-actions
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: taskpulse-api
