{
 "title": "Pranav Production Dashboard",
 "tags": [
  "pranav-app",
  "kubernetes",
  "devops"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Application Golden Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Request Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pranav-app_http_requests_total[1m])) by (method, route)",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "P95 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pranav-app_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "HTTP 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(pranav-app_http_requests_total{status=~\"5..\"}[5m])) / sum(rate(pranav-app_http_requests_total[5m]))) * 100",
     "legendFormat": "5xx error %"
    }
   ]
  },
  { "title": "Infrastructure & Pod Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active Pod Replicas vs Desired",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"pranav-app\"}",
     "legendFormat": "Available Pods"
    },
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"pranav-app\"}",
     "legendFormat": "Desired Pods"
    }
   ]
  },
  {
   "title": "Pod Memory Usage (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"pranav-app\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}