apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pranav-app-service-monitor
  namespace: pranav-prod
  labels:
    app.kubernetes.io/name: pranav-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pranav-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
