apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudnexus-service-monitor
  namespace: cloudnexus-prod
  labels:
    app.kubernetes.io/name: cloudnexus
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnexus
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
