apiVersion: v1
kind: Service
metadata:
  name: pulsewatch-service
  namespace: observability-demo
  labels:
    app: pulsewatch-api
    tier: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: pulsewatch-api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
