apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pranav.fullname" . }}-secret
  labels:
    {{- include "pranav.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
  API_SECRET_KEY: {{ .Values.secrets.API_SECRET_KEY | quote }}
