apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv-demo
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-storage
  hostPath:
    path: /mnt/data/manual-pv-demo
