apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-pvc-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-storage
  resources:
    requests:
      storage: 500Mi
