apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudnexus-project
  namespace: argocd
spec:
  description: "CloudNexus Production GitOps Management Project"
  sourceRepos:
    - "https://github.com/Pranav-learner/DevOps_assignment.git"
  destinations:
    - namespace: cloudnexus-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
