apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudstore-chart.fullname" . }}-secret
  labels:
    {{- include "cloudstore-chart.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | default "Q2xvdWRTdG9yZTIwMjYhIQ==" | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecret | default "ZXh0cmVtZWx5LXNlY3VyZS1qd3QtdG9rZW4tc2VjcmV0" | b64enc | quote }}
  PAYMENT_GATEWAY_KEY: {{ .Values.secrets.paymentKey | default "cGtfbGl2ZV85OTQ4Mjd4eXphYmM=" | b64enc | quote }}
