apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnexus-troubleshoot-imagepull
  namespace: cloudnexus-prod
  labels:
    app: troubleshoot-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troubleshoot-2
  template:
    metadata:
      labels:
        app: troubleshoot-2
    spec:
      containers:
        - name: app
          # REMEDIATION: Correct image tag to existing 1.0.0 image
          image: cloudnexus:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_PASSWORD
              value: "demo-pass"
