apiVersion: v1
kind: Pod
metadata:
  name: liveness-http-demo
  labels:
    app: liveness-http-demo
spec:
  containers:
    - name: web-app
      image: nginx:alpine
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
