apiVersion: v1
kind: Secret
metadata:
  name: taskflow-db-secret
  namespace: taskflow-prod
type: Opaque
stringData:
  POSTGRES_DB: taskflow
  POSTGRES_USER: taskflow
  POSTGRES_PASSWORD: TaskFlowSecurePass2026!
