apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudnexus-data-pvc
  namespace: cloudnexus-prod
  labels:
    app: cloudnexus-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
