apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pranav-app-data-pvc
  namespace: pranav-prod
  labels:
    app: pranav-app-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
