apiVersion: v1
kind: Secret
metadata:
  name: pranav-app-secrets
  namespace: pranav-prod
  labels:
    app: pranav-app-api
type: Opaque
stringData:
  DB_PASSWORD: "SuperSecureProductionPassword2026!"
  API_SECRET_KEY: "pranav-app-jwt-hs256-signature-key"
