apiVersion: v1
kind: Secret
metadata:
  name: cloudnexus-secrets
  namespace: cloudnexus-prod
  labels:
    app: cloudnexus-api
type: Opaque
stringData:
  DB_PASSWORD: "SuperSecureProductionPassword2026!"
  API_SECRET_KEY: "cloudnexus-jwt-hs256-signature-key"
